server:
  port: 8888

spring:
  cloud:
    config:
      server:
        svn:
          uri: https://github.com/royclarkson/svn-config-server
        git:
          uri: https://github.com/pcf-guides/configuration-server-config-repo

logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
